# Generated by Django 5.1.6 on 2025-05-13 16:59

from django.db import migrations, models


def set_user_level_to_10(apps, schema_editor):
    User = apps.get_model(
        "accounts", "User"
    )  # Use 'auth' if you're using the default User model
    User.objects.update(user_level=10)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("dispatcharr_channels", "0019_channel_tvc_guide_stationid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="channel_groups",
        ),
        migrations.AddField(
            model_name="user",
            name="channel_profiles",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="dispatcharr_channels.channelprofile",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_level",
            field=models.IntegerField(
                choices=[(0, "Streamer"), (1, "ReadOnly"), (10, "Admin")], default=0
            ),
        ),
        migrations.RunPython(set_user_level_to_10),
    ]
