# Generated by Django 5.1.6 on 2025-03-14 17:16

from django.db import migrations

def create_proxy_stream_profile(apps, schema_editor):
    StreamProfile = apps.get_model("core", "StreamProfile")
    StreamProfile.objects.create(
        profile_name="Proxy",
        command="",
        parameters="",
        locked=True,
        is_active=True,
        user_agent="1",
    )

    StreamProfile.objects.create(
        profile_name="Redirect",
        command="",
        parameters="",
        locked=True,
        is_active=True,
        user_agent="1",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_set_locked_stream_profiles'),
    ]

    operations = [
    ]
