# Generated by Django 5.1.6 on 2025-03-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_create_proxy_and_redirect_stream_profiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamprofile',
            old_name='profile_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='useragent',
            old_name='user_agent_name',
            new_name='name',
        ),
    ]
