# Generated by Django 5.1.6 on 2025-06-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_default_active_m3u_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffering_timeout', models.IntegerField(default=15, help_text='Seconds to wait for buffering before switching streams')),
                ('buffering_speed', models.FloatField(default=1.0, help_text='Speed threshold to consider stream buffering (1.0 = normal speed)')),
                ('redis_chunk_ttl', models.IntegerField(default=60, help_text='Time in seconds before Redis chunks expire')),
                ('channel_shutdown_delay', models.IntegerField(default=0, help_text='Seconds to wait after last client before shutting down channel')),
                ('channel_init_grace_period', models.IntegerField(default=5, help_text='Seconds to wait for first client after channel initialization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proxy Settings',
                'verbose_name_plural': 'Proxy Settings',
            },
        ),
    ]
