FROM alpine

ENV PATH="/dispatcharrpy/bin:$PATH" \
    VIRTUAL_ENV=/dispatcharrpy \
    DJANGO_SETTINGS_MODULE=dispatcharr.settings \
    PYTHONUNBUFFERED=1

RUN apk add \
        python3 \
        python3-dev \
        gcc \
        musl-dev \
        linux-headers \
        py3-pip \
        ffmpeg \
        streamlink \
        vlc \
        libpq-dev \
        gcc \
        py3-virtualenv  \
        uwsgi \
        uwsgi-python \
        nodejs \
        npm \
        git \
        redis

COPY ./ /app/

RUN \
    mkdir /data && \
    virtualenv /dispatcharrpy && \
    cd /app && \
    /dispatcharrpy/bin/pip install --no-cache-dir -r requirements.txt && \
    cd /app/frontend && \
    npm install && \
    cd /app && \
    python manage.py collectstatic --noinput || true

# Cleanup
RUN \
    apk del \
        git \
        gcc \
        musl-dev \
        python3-dev \
        linux-headers

WORKDIR /app

CMD ["/usr/sbin/uwsgi", "--ini", "uwsgi.ini"]
# CMD ["gunicorn", "--workers=4", "--worker-class=gevent", "--timeout=300", "--bind", "0.0.0.0:5656", "dispatcharr.wsgi:application"]
