# Generated by Django 5.1.6 on 2025-04-09 22:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField(max_length=2048)),
                ('download_type', models.CharField(choices=[('epg', 'EPG'), ('m3u', 'M3U'), ('custom', 'Custom')], max_length=10)),
                ('frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom Schedule')], max_length=10)),
                ('cron_expression', models.CharField(blank=True, max_length=100, null=True)),
                ('hour', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('scheduled', 'Scheduled'), ('downloading', 'Downloading'), ('success', 'Success'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('last_failure', models.DateTimeField(blank=True, null=True)),
                ('custom_filename', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_agent', models.CharField(blank=True, default='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36', max_length=500)),
                ('custom_headers', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('scheduled', 'Scheduled'), ('downloading', 'Downloading'), ('success', 'Success'), ('failed', 'Failed')], default='downloading', max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('download_speed', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('saved_path', models.CharField(blank=True, max_length=512)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='downloads.downloadtask')),
            ],
            options={
                'verbose_name_plural': 'Download histories',
            },
        ),
    ]
