# Generated by Django 5.1.6 on 2025-03-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='channel_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='url',
        ),
        migrations.RenameField(
            model_name='stream',
            old_name='custom_url',
            new_name='url',
        ),
    ]
