# Generated by Django 5.1.6 on 2025-03-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0003_channel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Whether this is a user-created stream or from an M3U account'),
        ),
    ]
