# Generated by Django 5.1.6 on 2025-03-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0006_migrate_stream_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='group_name',
        ),
    ]
