# Generated by Django 5.1.6 on 2025-03-26 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0008_stream_stream_hash'),
        ('epg', '0004_epgdata_epg_source_alter_epgdata_tvg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='tvg_name',
        ),
        migrations.AddField(
            model_name='channel',
            name='epg_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='epg.epgdata'),
        ),
    ]
