# Generated by Django 5.1.6 on 2025-04-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0009_remove_channel_tvg_name_channel_epg_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='custom_properties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
