# Generated by Django 5.1.6 on 2025-04-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0012_channelprofile_channelprofilemembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
