# Generated by Django 5.1.6 on 2025-04-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0014_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='custom_properties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
