# Generated by Django 5.1.6 on 2025-04-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0016_channelstream_unique_channel_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelgroup',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
