# Generated by Django 5.1.6 on 2025-05-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0017_alter_channelgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_number',
            field=models.FloatField(db_index=True),
        ),
    ]
