# Generated by Django 5.1.6 on 2025-04-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0017_alter_channelgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelgroupm3uaccount',
            name='custom_properties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
