# Generated by Django 5.1.6 on 2025-05-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0018_channelgroupm3uaccount_custom_properties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='tvc_guide_stationid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
