# Generated by Django 5.1.6 on 2025-05-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0019_channel_tvc_guide_stationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_number',
            field=models.FloatField(db_index=True),
        ),
    ]
