# Generated by Django 5.1.6 on 2025-05-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0020_alter_channel_channel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='user_level',
            field=models.IntegerField(default=0),
        ),
    ]
