# Generated by Django 5.1.6 on 2025-07-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0021_channel_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelgroupm3uaccount',
            name='auto_channel_sync',
            field=models.BooleanField(default=False, help_text='Automatically create/delete channels to match streams in this group'),
        ),
        migrations.AddField(
            model_name='channelgroupm3uaccount',
            name='auto_sync_channel_start',
            field=models.FloatField(blank=True, help_text='Starting channel number for auto-created channels in this group', null=True),
        ),
    ]
