# Generated by Django 5.1.6 on 2025-07-13 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0021_channel_user_level'),
        ('m3u', '0012_alter_m3uaccount_refresh_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='auto_created',
            field=models.BooleanField(default=False, help_text='Whether this channel was automatically created via M3U auto channel sync'),
        ),
        migrations.AddField(
            model_name='channel',
            name='auto_created_by',
            field=models.ForeignKey(blank=True, help_text='The M3U account that auto-created this channel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_created_channels', to='m3u.m3uaccount'),
        ),
        migrations.AddField(
            model_name='channelgroupm3uaccount',
            name='auto_channel_sync',
            field=models.BooleanField(default=False, help_text='Automatically create/delete channels to match streams in this group'),
        ),
        migrations.AddField(
            model_name='channelgroupm3uaccount',
            name='auto_sync_channel_start',
            field=models.FloatField(blank=True, help_text='Starting channel number for auto-created channels in this group', null=True),
        ),
    ]
