# Generated by Django 5.1.6 on 2025-01-XX XX:XX

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0022_channelgroupm3uaccount_auto_channel_sync_and_more'),
        ('m3u', '0003_create_custom_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='auto_created',
            field=models.BooleanField(default=False, help_text='Whether this channel was automatically created via M3U auto channel sync'),
        ),
        migrations.AddField(
            model_name='channel',
            name='auto_created_by',
            field=models.ForeignKey(blank=True, help_text='The M3U account that auto-created this channel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_created_channels', to='m3u.m3uaccount'),
        ),
    ]
