# Generated by Django 5.1.6 on 2025-02-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epgdata',
            name='channel',
        ),
        migrations.AddField(
            model_name='epgdata',
            name='tvg_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='tvg_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
