# Generated by Django 5.1.6 on 2025-03-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epgsource',
            name='file_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
