# Generated by Django 5.1.6 on 2025-03-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0002_epgsource_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epgdata',
            name='tvg_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
