# Generated by Django 5.1.6 on 2025-03-26 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0003_alter_epgdata_tvg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='epgdata',
            name='epg_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epgs', to='epg.epgsource'),
        ),
        migrations.AlterField(
            model_name='epgdata',
            name='tvg_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
