# Generated by Django 5.1.6 on 2025-03-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0004_epgdata_epg_source_alter_epgdata_tvg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdata',
            name='custom_properties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='epgdata',
            unique_together={('tvg_id', 'epg_source')},
        ),
    ]
