# Generated by Django 5.1.6 on 2025-04-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0008_epgsource_created_at_epgsource_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epgsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when this source was created'),
        ),
        migrations.AlterField(
            model_name='epgsource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Time when this source was last updated'),
        ),
    ]
