# Generated by Django 5.1.6 on 2025-05-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0007_epgsource_status_epgsource_last_error'),
        ('epg', '0009_alter_epgsource_created_at_and_more'),
    ]

    operations = [
    ]
