# Generated by Django 5.1.6 on 2025-05-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0011_update_epgsource_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epgsource',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('fetching', 'Fetching'), ('parsing', 'Parsing'), ('error', 'Error'), ('success', 'Success'), ('disabled', 'Disabled')], default='idle', max_length=20),
        ),
    ]
