# Generated by Django 5.1.6 on 2025-05-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0012_alter_epgsource_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epgsource',
            name='refresh_interval',
            field=models.IntegerField(default=0),
        ),
    ]
