# Generated by Django 5.1.6 on 2025-05-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0013_alter_epgsource_refresh_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='epgsource',
            name='extracted_file_path',
            field=models.CharField(blank=True, help_text='Path to extracted XML file after decompression', max_length=1024, null=True),
        ),
    ]
