# Generated by Django 5.1.6 on 2025-05-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0013_alter_epgsource_refresh_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='epgsource',
            name='original_file_path',
            field=models.CharField(blank=True, help_text='Original path to compressed file before extraction', max_length=1024, null=True),
        ),
    ]
