# Generated by Django 5.1.6 on 2025-03-19 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_m3u_hash_settings'),
        ('m3u', '0003_create_custom_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='m3uaccount',
            name='stream_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m3u_accounts', to='core.streamprofile'),
        ),
    ]
