# Generated by Django 5.1.6 on 2025-02-21 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('m3u', '0003_m3uaccount_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m3uaccount',
            name='user_agent',
            field=models.ForeignKey(blank=True, help_text='The User-Agent associated with this M3U account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m3u_accounts', to='core.useragent'),
        ),
        migrations.DeleteModel(
            name='UserAgent',
        ),
    ]
