# Generated by Django 5.1.6 on 2025-03-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0004_m3uaccount_stream_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='m3uaccount',
            name='custom_properties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
