# Generated by Django 5.1.6 on 2025-05-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0010_add_status_fields_and_remove_auto_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m3uaccount',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('fetching', 'Fetching'), ('parsing', 'Parsing'), ('error', 'Error'), ('success', 'Success'), ('pending_setup', 'Pending Setup'), ('disabled', 'Disabled')], default='idle', max_length=20),
        ),
    ]
