# Generated by Django 5.1.6 on 2025-05-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m3u', '0011_alter_m3uaccount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m3uaccount',
            name='refresh_interval',
            field=models.IntegerField(default=0),
        ),
    ]
